### ISSUE TITLE
LaunchDarkly.CommonSdk.StrongName > 2.6.1 contains no namespaces/classes

### ISSUE THREAD

**Issue by wags1999** [launchdarkly/dotnet-server-sdk#107]
**Describe the bug**
After upgrading to any version of LaunchDarkly.CommonSdk.StrongName greater than 2.6.1, the compiler can no longer resolve the references to the LaunchDarkly.Client.User class.  Upon further inspection, the LaunchDarkly.CommonSdk.StrongName assembly doesn't contain any namespaces or classes.
![image](https://user-images.githubusercontent.com/5712472/65897835-d114f080-e375-11e9-9b44-59b5d34005d3.png)

**To reproduce**
Tried with both .NET Framework 4.6.1 and .NET Core 2.2:
- Create new .NET Console App project.
- Add LaunchDarkly.ServerSdk 5.7.1 NuGet package.
- Install LaunchDarkly.CommonSdk.StrongName 4.0.1 NuGet package.
![image](https://user-images.githubusercontent.com/5712472/65897710-872c0a80-e375-11e9-932f-045915bf8399.png)

**Expected behavior**
Code compiles

**SDK version**
Problem appears in LaunchDarkly.CommonSdk.StrongName 3.0.0, 3.1.0, and 4.1.0.

**Language version, developer tools**
Tried with .NET Framework 4.6.1 and .NET Core 2.2

**OS/platform**
Windows

**Additional context**
My organization hasn't purchased LaunchDarkly yet; we're still evaluating it.  Your responsiveness is appreciated!

**Comment by eli-darkly** [comment]
Please don't upgrade the CommonSdk package separately from the SDK. It is supposed to use the version that the SDK has a dependency on, which should be installed automatically as a transitive dependency. Whenever we need to do a bugfix release of CommonSdk, we do a corresponding release of the SDK.

Also, since we follow semantic versioning conventions, you should never expect for a higher major version to be backward-compatible. The 3.x and 4.x releases of CommonSdk exist to support a different .NET-based SDK (Xamarin) and will be used in a future major version of the .NET SDK, but do not work with .NET SDK 5.x.

**Comment by wags1999** [comment]
OK.  Thanks for the quick response!
