### ISSUE TITLE
Logging setup is not clear

### ISSUE THREAD

**Issue by spowser** [launchdarkly/dotnet-server-sdk#116]
LaunchDarkly.ServerSdk version 5.8.0

I am attempting to get DEBUG level logging information from the Launch Darkly client in an ASP.NET Core 2.2 application.  The documentation currently points me to another GitHub page that has information that recommends how to setup logging in a web.config or app.config.  Our project has neither of those and uses the appsettings.json file.

Do you have any clear instructions on enabling DEBUG logs for the Launch Darkly client in an ASP.NET Core application using the appsettings.json file?

**Comment by eli-darkly** [comment]
Well, the SDK delegates all of that stuff to Common.Logging, so this is really a question about Common.Logging configuration. There's a discussion about that [here](https://github.com/net-commons/common-logging/issues/153) where the first reply includes an example of an appsettings.json file - however, the specific properties you would want to put in that file would depend on how you actually want the logging to happen, e.g. using the NLog adapter and a file destination as they have it in that example, or something else.

For instance, to send output to the console and enable DEBUG level, I _think_ the file would look more like this:

```
{
  "LogConfiguration": {
    "factoryAdapter": {
      "type": "Common.Logging.Simple.ConsoleOutLoggerFactoryAdapter, Common.Logging",
      "arguments": {
        "level": "DEBUG"
      }
    }
  }
}
```

However, I can't guarantee that that's right because I haven't tried using appsettings.json. More general documentation about Common.Logging is [here](http://net-commons.github.io/common-logging/).

**Comment by spowser** [comment]
I have added the following configuration to my appsettings.json with no effect.  We just want simple logging as console output.

`"LogConfiguration": {
        "factoryAdapter": {
            "type": "Common.Logging.Simple.DebugLoggerFactoryAdapter, Common.Logging",
            "arguments": {
                "level": "All",
                "showDateTime": true,
                "showLogName": true,
                "showLevel": true,
                "dateTimeFormat": "yyyy/MM/dd HH:mm:ss.fff"
            }
        }
    }`

This is in their example code for a .NET Core client.  What's interesting is that our project is seeing 0 log output from the Launch Darkly SDK.  Without logging we are kinda flying blind using this SDK.

Side note:  The Common.Logging library for .NET seems to be either dead or having issues keeping it maintained.

**Comment by eli-darkly** [comment]
Did you also try the configuration that I suggested? `ConsoleOutLoggerFactoryAdapter` and `DebugLoggerFactoryAdapter` are not the same. The former writes to standard output; the latter writes to `System.Diagnostics.Debug`, which I believe does not show up anywhere by default unless you explicitly configure it to.

> I also noticed their issue tracking is riddled with people complaining about their library working in .NET Core 2.0 environments.

The issues I'm seeing there are about incompatibilities of specific logging packages, such as NLog, with .NET Core 2.0. Common.Logging is just a common interface over these various logging adapters for NLog, Log4net, etc. If you are just using console output then those are irrelevant.

It's true that Common.Logging has not been maintained for a while. We adopted it for flexibility since a lot of people did not want to use the MS log framework, and Common.Logging supported  the other popular log frameworks people might want to use, but we will probably be moving away from it in a future major version update of the .NET SDK.

What we might replace it with is still up in the air. We've had various suggestions, but virtually anything we might choose is going to be unacceptable to someone— there just isn't enough of a consensus about logging in .NET, so it's quite a challenge when providing a library. We might take the approach of defining our own logging abstraction, with a default console implementation, and providing adapters to make it use another logging framework... that is, very much like what Common.Logging does, but with a much simpler interface.

**Comment by spowser** [comment]
Yes, I also tried that config as well.

    {
     "LogConfiguration": {
             "factoryAdapter": {
                 "type": "Common.Logging.Simple.ConsoleOutLoggerFactoryAdapter, Common.Logging",
                 "arguments": {
                     "level": "All",
                     "showDateTime": true,
                     "showLogName": true,
                     "showLevel": true,
                     "dateTimeFormat": "yyyy/MM/dd HH:mm:ss.fff"
                 }
             }
     }

**Comment by spowser** [comment]
It would be super helpful to have just a simple sample project written in .NET Core 2.0+ with an appsettings.json configured to log out what the SDK is doing.

**Comment by eli-darkly** [comment]
That's reasonable— we could add a project like that to [`hello-dotnet`](https://github.com/launchdarkly/hello-dotnet).

**Comment by eli-darkly** [comment]
On the original question, though - when you say that you added that data to `appsettings.json` and saw no effect, do you mean that was the _only_ change you made? Because if you look at [the example](https://github.com/net-commons/common-logging/issues/153#issuecomment-343840193) in the link I provided, it is not just a matter of putting things in that file; you also need to add .NET code to tell it to actually _use_ that configuration:

```
LogConfiguration logConfiguration = new LogConfiguration();
config.GetSection("LogConfiguration").Bind(logConfiguration);
LogManager.Configure(logConfiguration);
```

In the sample code, `LogConfiguration` and `LogManager` are types from Common.Logging, and `config` is the `Microsoft.Extensions.Configuration.IConfiguration` object for your application (in the rest of the sample code there, they created that explicitly, but normally it would be passed in by dependency injection).

When I added that code to an ASP.NET Core version of the `hello-dotnet` code, and used the configuration from your example with `DebugLoggerFactoryAdapter`, it worked as expected— that is, output went to the Debug window in Visual Studio, since that is what `DebugLoggerFactoryAdapter` does.

If on the other hand you want logging to go to standard output, or to a file, you would need to use one of the logging frameworks that Common.Logging can delegate to, such as log4net or NLog, and configure that one however you wish. Common.Logging is supposed to provide a basic adapter for writing to standard output without using another framework— `ConsoleOutLoggerFactoryAdapter`— but for some reason it is not included in the .NET Standard version of Common.Logging. That's an annoying omission since it's a common use case, so we might start providing a basic implementation of it in the SDK.

**Comment by eli-darkly** [comment]
Note that it's always possible to use programmatic configuration:

```
    var logProps = new Common.Logging.Configuration.NameValueCollection
    {
        { "level", "Debug" }
    };
    Common.Logging.LogManager.Adapter = new Common.Logging.Simple.DebugLoggerFactoryAdapter(logProps);
```

**Comment by spowser** [comment]
Thanks for the help on this.  Debug console is now working which gives us something.  The original ticket I was tasked with was surfacing console logs to DevOps so I'm going to need to figure something else out for that part.

**Comment by eli-darkly** [comment]
The easiest way to get console output, without using any of the Common.Logging adapters for other frameworks like NLog, is to use `Common.Logging.Simple.ConsoleOutLoggerFactoryAdapter`— except that they forgot to include that class in their .NET Core build. So the _second_ easiest way is to just copy their implementations of [`ConsoleOutLoggerFactoryAdapter`](https://github.com/net-commons/common-logging/blob/master/src/Common.Logging/Logging/Simple/ConsoleOutLoggerFactoryAdapter.cs) and [`ConsoleOutLogger`](https://github.com/net-commons/common-logging/blob/master/src/Common.Logging/Logging/Simple/ConsoleOutLogger.cs). The code is pretty straightforward, but that's still annoying, so as I said I think we should start providing an equivalent class that's built into the SDK in the future (for however long we continue to use Common.Logging).

**Comment by eli-darkly** [comment]
If you do that, then the `"type"` property in the config file would be `"X.ConsoleOutLoggerFactoryAdapter, Y"` where X is whatever namespace you put that class in, and Y is the name of your assembly.

**Comment by eli-darkly** [comment]
As of version 5.10.0, there is a `LaunchDarkly.Logging.ConsoleAdapter` class that serves the purpose mentioned in my earlier comment.
