### ISSUE TITLE
IFeatureStore interface issues

### ISSUE THREAD

**Issue by jjxtra** [launchdarkly/dotnet-server-sdk#137]
The `IFeatureStore` interface `All` method requires a complete new dictionary to store the results. The signature is a problem. If the return value could be of `string,IVersionedData` instead of `string,T` that would eliminate the need to create a separate dictionary.

```cs
/// <inheritdoc />
IDictionary<string, T> IFeatureStore.All<T>(VersionedDataKind<T> kind)
{
	if (cache.TryGetValue(kind, out var dict2))
	{
		Dictionary<string, T> result = new Dictionary<string, T>(dict2.Count);
		foreach (var kv in dict2)
		{
			result.Add(kv.Key, (T)kv.Value);
		}
		return result;
	}
	return new Dictionary<string, T>();
}
```

**Comment by eli-darkly** [comment]
Thanks for the suggestion, but I think the issue is moot now. There is a [6.0.0](https://github.com/launchdarkly/dotnet-server-sdk/blob/master/CHANGELOG.md) major version release currently in beta, soon to be GA. The data store and most other components in the SDK now work fairly differently, so there won't be any further changes to the interfaces in the 5.x code (changing an interface method signature would've been a breaking change requiring a new major version anyway). The equivalent method in the implementation of `InMemoryDataStore` in 6.0.0 doesn't copy the data structure, although copying is still necessary in other steps due to differences in how the data is stored.
