### ISSUE TITLE
.Net SDK does not trigger events when changes occur in files source

### ISSUE THREAD

**Issue by chifton** [launchdarkly/dotnet-server-sdk#144]
**Is this a support request?**
I would like to spot a bug in the .Net SDK.

**Describe the bug**
**.Net SDK does not trigger events when changes occur in source file (JSON, YAML), especially when we change flagValues nodes values.**
The flag rules are just updated in the SDK, **no event is triggered**, but **the documentation says it should**, as specified here https://github.com/launchdarkly/dotnet-server-sdk/blob/1a4371f952910bacdd605c1a5c7182b0a196a94a/src/LaunchDarkly.ServerSdk/Interfaces/IFlagTracker.cs#L33

**The error certainly occurs here, version always equals 1, thus the SDK does not see any change and does not trigger events.**
![image](https://user-images.githubusercontent.com/24291006/128924601-4a8ca515-5202-4761-bd5c-d3f3c4e73d09.png)

**To reproduce**
- Initialize an LDClient with a file as a toggle source, containing only flagValues node, as mentionned here:
https://docs.launchdarkly.com/sdk/features/flags-from-files
![image](https://user-images.githubusercontent.com/24291006/128924663-98329fc7-516b-4147-a3a5-aaa1e6c127ce.png)
 - Change a toggle value

**Expected behavior**
Event should be triggered if a flag value is updated in the file

**Logs**
No logs, but the above screenshot may show where the error occurs.

**SDK version**
6.2.0

**Language version, developer tools**
.Net 5

**OS/platform**
Any platform

**Comment by eli-darkly** [comment]
Thanks for pointing this out. Indeed, the current documentation comment is wrong to say that change events will work with the file data source; currently they won't, for exactly the reason you pointed out, that it's not incrementing the version number.

The simplest way for us to address that would be to make it increment the version number for _every_ flag each time it detects new file data. That would mean that you would get a change event for every flag, even if that particular flag wasn't changed in the file; I don't know if that would be a problem for your application. But trying to make it increment the version only for flags that really did change would be a lot more difficult (since file data can include full flag configurations, not just values— so it would have to keep a copy of the whole configuration for every flag, which could be quite large, and do a deep equality comparison). So I'm leaning toward the simpler change.

**Comment by eli-darkly** [comment]
We've released version 6.2.1, which should fix this.
