### ISSUE TITLE
Confusion when going from context to user

### ISSUE THREAD

**Issue by S3j5b0** [launchdarkly/dotnet-server-sdk#161]
Hi, I need to implement launchnightly for a small project. 

I have looked at a lot other similar projects, but they mostly use the now deprecated `launchnightly.client` the nuget page for that one leads me to this one, so I tried giving it a go.

One thing that is new in `LaunchDarkly.Sdk.Server`, is that context is now used instead of user. The docs on the context says this:

```
Context is the newer replacement for the previous, less flexible LaunchDarkly.Sdk.User
type. The current SDK still supports User, but Context is now the preferred model and may entirely replace User in the future.
```

I then have this old way of constructing a user, that I would like this replicate:

```
    private readonly User _defaultUser = User
      .WithKey(Guid.Empty.ToString("N"))
      .AndAnonymous(true)
      .AndEmail(string.Empty)
      .AndFirstName("n/a")
      .AndCustomAttribute("platform", "dingondg")
      .AndLastName(".");

```

So, I thought since the context was just a more flexible replacement for the User, so I thought that the contextbuilder would have functions that mirror those seen above.

This is not the case, there is a `Anonymos` and `name` function, apart from that, the contextbuilder doesnt have any mirroring functions.
Especially the "customattribute` I would like to be able to set, but there is absolutely nothing about the context that indicates which field is correponding to it. Leaving me kinda in the dark.

The documenation also says that the current sdk still support user. I can access the type, but the only of the builder functions available to me, is `withkey`, so it's not even obvious how I should replicate the old code with the new sdk?

Would it be possible to make it more clear which old fields in User, correspond to which new fields in context? Or if it could be possible to make the old way of using "User" available again?

**Comment by eli-darkly** [comment]
Have you looked at the migration guide pages in the online docs? The [6.x to 7.0 migration guide](https://docs.launchdarkly.com/sdk/server-side/dotnet/migration-6-to-7) discusses differences between the user model and the context model in the .NET SDK, and includes links to more pages that discuss the conceptual differences in a non-SDK-specific way.

I'll address your specific questions as best I can here, but if you haven't read those docs, reading them is strongly recommended.

I also notice that you have been using a _very_ old version of the SDK (the package hasn't been called `LaunchDarkly.Client` for nearly 4 years), so, for instance, the specific `User` methods you're using in that code excerpt were already different— unrelated to the Context changes.

**Comment by eli-darkly** [comment]
(Also, the product is called LaunchDarkly, not launchnightly)

**Comment by eli-darkly** [comment]
> Especially the "customattribute` I would like to be able to set, but there is absolutely nothing about the context that indicates which field is correponding to it. Leaving me kinda in the dark.

"AndCustomAttribute" was not a field, it was a method— and it's a method that hasn't existed in a while, because again, you have been using a very out-of-date SDK; that method in the current `User` builder is called `Custom` and is documented [here](https://launchdarkly.github.io/dotnet-server-sdk/api/LaunchDarkly.Sdk.IUserBuilder.html#LaunchDarkly_Sdk_IUserBuilder_Custom_System_String_System_String_). The equivalent method in the `Context` builder is called `Set`, because the SDK doesn't really have a concept of "custom" attributes any more— you just set whatever attribute names you want. If you look at the [API docs for the Context builder](https://launchdarkly.github.io/dotnet-server-sdk/api/LaunchDarkly.Sdk.ContextBuilder.html), there are not a lot of methods and it clearly states that `Set` is the method for setting any attribute by name, so I'm surprised that that was hard to find.

**Comment by eli-darkly** [comment]
> The documenation also says that the current sdk still support user. I can access the type, but the only of the builder functions available to me, is withkey, so it's not even obvious how I should replicate the old code with the new sdk?

I think the problem here is that the User methods had already changed years ago, unrelated to the Context changes, but you have been using a very old SDK so you weren't familiar with how User works now. The user builder methods did not change in the 7.0.0 release; they have been mostly the same ever since 5.7.0. The modern equivalent of the code sample you showed would look like this:

```csharp
private readonly User _defaultUser = User.Builder(Guid.Empty.ToString("N"))
      .Anonymous(true)
      .Email(string.Empty)
      .FirstName("n/a")
      .Custom("platform", "dingondg")
      .LastName(".")
      .Build();
```

**Comment by kinyoklion** [comment]
I don't see any follow up questions or activity on this, so I am going to close this issue. Please let me know if you have any further questions.
